### PR TITLE
Handle error conditions

### PR DESCRIPTION
**Pull request by RogerSelwyn**
Handle errors for powered of Sky Q (such as when it goes to sleep overnight). Also deal with single service being returned from call in _getSoapControlURL

### CODE REVIEW

**Comment by mattrayner** [comment]
I am very excited for this update

**Comment by RogerSelwyn** [comment]
Please be patient, not ready yet

**Comment by RogerSelwyn** [comment]
And I'm removing this pull request, because I will be releasing on my repository, because this one seems to have gone dead.

**Comment by RogerSelwyn** [comment]
> I am very excited for this update

I have released a new version here - https://community.home-assistant.io/t/custom-component-skyq-media-player/140306/297

**Pull request closed without merging**
